### ISSUE TITLE
Custom Domain Support

### ISSUE THREAD

**Issue by ghost** [Arachnid/bloggart#38]
obviously custom domains are supported ( e.g. http://blog.notdot.net ) via the gae add domain but how can i login to the blog as an admin with a email address from that domain ( e.g. something@notdot.net ) instead of my @gmail account 

note: yes my domain is a google apps domain ( http://blog.brandonholtsclaw.com )

**Comment by Arachnid** [comment]
If you created the App Engine app with that apps domain as the auth domain, admins must be from that domain. If you created it to use Google Accounts, you can add admins from Apps domains, but they will not be able to log in to the /admin/ interface. This is due to a known issue with App Engine, and applies to all apps.

**Comment by ghost** [comment]
ahh yes , i fall into the second category ( created to use google accounts and there is a domain user as an admin but cant login )
