### ISSUE TITLE
[pull request] fix dates in atom.xml

### ISSUE THREAD

**Issue by rctay** [Arachnid/bloggart#44]
The patch is available [here](http://github.com/rctay/bloggart/tree/rc/fix-atom).

**Comment by Arachnid** [comment]
Hi,

Lots of good patches in your repo - thanks! Sorry I've taken so long to get to them.

A lot of them break the general style of Bloggart, though. For example, introducing new handler scripts for specific URLs, rather than adding them to the existing handler script, or expecting callers of a model to generate keys themselves, rather than providing a factory method. Do you have any interest in reworking any of it? If not, I'll include your changes, then patch a bit for style/consistency.

**Comment by Arachnid** [comment]
Sorry, that should've been directed at someone else. :)

**Comment by Arachnid** [comment]
Oops, no it wasn't - for some reason, you appear twice in my fork queue. :)

**Comment by rctay** [comment]
Hi Nick,

thanks for looking through them. I'll look through your comments and get back to you soon.

Just a note - I've organized my patches into topic branches - eg. [rc/fix-atom](http://github.com/rctay/bloggart/tree/rc/fix-atom), [rc/defer-config](http://github.com/rctay/bloggart/tree/rc/defer-config) - so you can just pick and merge in those that you think are fine.

I'm particularly interested at getting the fixes in - they are prefixed with `rc/fix-`, FYI.

Please ignore `rc/master` - although it's mostly merges of these topics, it's also has some stuff that are specific to myself.
