### ISSUE TITLE
A way to disable caching

### ISSUE THREAD

**Issue by zencd** [Arachnid/bloggart#48]
It's a big trouble to edit templates currently - after each update a user is required to update a blog entry to make the changes visible.

It'd be quite useful for me to have a config variable turning off the internal caching system. Or how do you debug changes in templates?

**Comment by Arachnid** [comment]
This is impossible - the entire site is built around statically generating content ahead of time. The generated content isn't a cache.

**Comment by zencd** [comment]
Maybe I understood the system design incorrectly... But the problem remains actual: it's hardly possible to debug templates/html/css without a way to review introduced chages.

I thought the solution could be to instruct the blog system to produce completely fresh HTML upon each request. Well, it's impossible. Then is there any trick to debug/design templates without the need to update blog posts each time a blog owner want to see changes?

**Comment by Arachnid** [comment]
The problem is that the system that serves up the pages is completely divorced from the system that generates them - by design, as it happens.

The admin console has a 'regenerate all' button - that's your best option for testing changes to the templates. Or, view the admin console itself, which currently uses the same skin.
